version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/webapp
hooks:
  BeforeInstall:
    - location: ./beforeinstall.sh
      runas: ubuntu
  ApplicationStart:
    - location: ./runapp.sh
      runas: ubuntu
