version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          TEST_DATABASE_URL: postgresql://postgres@localhost:5432/postgres
      - image: circleci/postgres:9.6.5-alpine-ram
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: whoami
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE users(id uuid NOT NULL,account_created character varying(255));"
    steps:
      - checkout
      - run:
          name: compile and run unit test
          command: mvn package
  build_deploy:
    docker:
      - image: circleci/openjdk:8-jdk  
    steps:
      - checkout
      - run:
          name: build push image
          command: echo "hello world from build and deploy!"

workflows:
  version: 2
  pr_check_workflow:
    jobs:
    - pr_check
  build_deploy-workflow:
    jobs:
    - build_deploy:
          filters:
            branches:
              only: master   
